server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.json$ {
        add_header Cache-Control "no-cache";
        add_header Content-Type "application/json; charset=utf-8";
    }

    location ~* \.(css|js)$ {
        expires 1h;
        add_header Cache-Control "public, immutable";
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;
    gzip_min_length 1000;
}
